name: Storybook Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.storybook/**'
      - '*.md'
  workflow_dispatch:

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 실행 제한 (한 번에 하나의 배포만)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 스토리북 빌드 Job
  build:
    name: 스토리북 빌드
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Corepack 활성화
        run: corepack enable

      - name: pnpm 설정
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: 의존성 설치
        run: pnpm install

      - name: 타입 검사
        run: pnpm run type-check

      - name: 스토리북 빌드
        run: pnpm run build-storybook
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: GitHub Pages 설정
        uses: actions/configure-pages@v4

      - name: 빌드된 스토리북 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

  # GitHub Pages 배포 Job
  deploy:
    name: GitHub Pages 배포
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: GitHub Pages에 스토리북 배포
        id: deployment
        uses: actions/deploy-pages@v4